### ISSUE TITLE
Could not use language specific url

### ISSUE THREAD

**Issue by Ley21** [viion/XIVDB-Tooltips#11]
If I try to use for example de.xivdb.com/.... as url link it wont replace it with the tooltip.
Also when I try to change the base url over the setting like I change the language.

**Comment by viion** [comment]
I don't think its parsing links correctly that contain the language flag, I will look into it.

**Comment by Ley21** [comment]
Hello, how is this issue going on. I currently working on an site with also tooltip support and multilanguage support. Currtently just the englisch part of the side supports tooltips.

**Comment by viion** [comment]
Hello Ley,

Did your commit fix work at all? I can look at this this weekend, its probably quite simple. I need to do some amends as well because I would like it so that if a link is fr.xivdb.com it requests a french tooltip instead of an English one, which is a bit more tricker (as tooltips are batch requested, and can contain any language)

**Comment by viion** [comment]
Hello!

Closing this as your PR did solve the issue :)

Updated the example: http://codepen.io/viion/full/mVzYRQ/
